// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import concourse "github.com/concourse/go-concourse/concourse"
import mock "github.com/stretchr/testify/mock"
import rc "github.com/concourse/fly/rc"

// Authenticator is an autogenerated mock type for the Authenticator type
type Authenticator struct {
	mock.Mock
}

// GetToken provides a mock function with given fields: client, username, password
func (_m *Authenticator) GetToken(client concourse.Client, username string, password string) (*rc.TargetToken, error) {
	ret := _m.Called(client, username, password)

	var r0 *rc.TargetToken
	if rf, ok := ret.Get(0).(func(concourse.Client, string, string) *rc.TargetToken); ok {
		r0 = rf(client, username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rc.TargetToken)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(concourse.Client, string, string) error); ok {
		r1 = rf(client, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
