// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import concourse "github.com/concourse/go-concourse/concourse"
import http "net/http"
import mock "github.com/stretchr/testify/mock"

// ClientFactory is an autogenerated mock type for the ClientFactory type
type ClientFactory struct {
	mock.Mock
}

// NewClient provides a mock function with given fields: url, httpClient, tracing
func (_m *ClientFactory) NewClient(url string, httpClient *http.Client, tracing bool) concourse.Client {
	ret := _m.Called(url, httpClient, tracing)

	var r0 concourse.Client
	if rf, ok := ret.Get(0).(func(string, *http.Client, bool) concourse.Client); ok {
		r0 = rf(url, httpClient, tracing)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(concourse.Client)
		}
	}

	return r0
}
